name: Deploy la api

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:


  deploy:
    name: Subir la api al server
    runs-on: ubuntu-latest

    steps:
    - name: Pillar Codigo
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.4
        extensions: mbstring,xmlrpc,soap,gd,xml,curl,zip,bcmath,tokenizer,json,mysql

    - name: Instalar dependencias de composer
      run: composer install --optimize-autoloader --no-progress --no-interaction --prefer-dist
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '22'
    - name: Instalar dependencias de npm
      run: npm install
    - name: Buil archivos npm
      run: npm run build
    - name: Configure SSH
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
    - name: Deploy
      uses: deployphp/action@master
      with:
        dep: deploy
        private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        options: |
         application: Backend API
         keep_releases: 5
         shared_dirs: ['./storage', './bootstrap/cache']
         shared_files: ['.env']
         writable_dirs: ['./storage', './bootstrap/cache']
    - name: Cambiar permisos
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.ADMIN }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          sudo chown deployer:www-data /var/www/api -R
        